language: node_js

node_js:
  - "8"

jobs:
  include:
    - stage: test
      script: npm run test
    - script: npm run coveralls
    - stage: build
      script: npm run build
    - stage: deploy
      script: echo 'not implemented'

stages:
  - test
  - build
  - deploy
